---
Join.message: "# §7Bienvenue sur §cFire§eWork !"
Login.message: "# §7Entrez /login (§6MotDePasse§7)."
Register.message: "# §7Entrez /register (§6MotDePasse§7)."
Register.success.message: "# §aVous etes connecté ,bon jeux!"
Login.success.message: "# §aVous etes connecté ,bon jeux!"
Already.registred.message: "§cVous etes deja enregistré!"
Already.logged-in.message: "§cVous etes deja connecté!"
Ip.login.message: "# §aVous etes connecté ,bon jeux !"
User.not.registered.message: "§cVous n'etes pas enregistrez!"
Incorrect.password.message: "§cMot de passe incorrect!"
Login.command.message: "§ecommande : /login (MotDePasse)"
Register.command.message: "§ecommande : /register (MotDePasse)"
...