name: FireAuth
main: fireauth\Main
version: 1.0.0
api: [3.0.0-ALPHA1,3.0.0-ALPHA4,3.0.0-ALPHA5]
author: SkySeven

commands:
  login:
    description: Login Command. 
  register:
    description: Register command.    
 
